services:
  postgres-server:    # The Postgres Database Service
    image: postgres:16.9 #some issues with version 17!
    restart: always
    environment:   # Username, password and database name variables
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      PG_DATA: /var/lib/postgresql/data/pgdata #data storage
    networks:
      zbx_net_backend:
       ipv4_address: 172.16.239.110
       aliases:
        - postgres-server
        - pgsql-server
        - pgsql-database

  zabbix-server:     # The main Zabbix Server Software Service
    image: zabbix/zabbix-server-pgsql:ubuntu-latest
    restart: always
    environment:   # The Postgres database value variable
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      ZBX_HISTORYSTORAGETYPES: log,text #Zabbix configuration variables
      ZBX_DEBUGLEVEL: 1
      ZBX_HOUSEKEEPINGFREQUENCY: 1
      ZBX_MAXHOUSEKEEPERDELETE: 5000
      DB_SERVER_HOST: postgres-server
      ZBX_NODEADDRESS: zabbix-server #fixes the UI error server not running! Issue# ZBX-26625
    depends_on:
      - postgres-server
    volumes:  # Volumes for scripts and related files you can add
      - /usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts
    ports:    # Port where Zabbix Server is available
      - 10051:10051
    networks:
      zbx_net_backend:
        ipv4_address: 172.16.239.105
        aliases:
         - zabbix-server-pgsql
         - zabbix-server
      zbx_net_frontend:
         ipv4_address: 172.16.238.105
         aliases:
          - zabbix-server-frontend

  zabbix-agent:   # Zabbix agent service that tracks usage and send to zabbix server
    image: zabbix/zabbix-agent2:latest
    ports:
     - "10050:10050"
    links:
     - zabbix-server:zabbix-server
    privileged: true
    pid: "host"
    restart: unless-stopped
    environment:
      - ZBX_SERVER_HOST=172.16.239.105 #the IP/Dns of Zabbix server
      - ZBX_HOSTNAME=zabbix-server
    networks:
     zbx_net_backend:
      ipv4_address: 172.16.239.106
      aliases:
       - zabbix-agent2
       - zabbix-agent2-passive

  zabbix-web:    # The main Zabbix web UI or interface 
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-latest
    restart: always
    environment:  # Postgre database variables
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      ZBX_POSTMAXSIZE: 64M
      PHP_TZ: "Australia/Melbourne"  
      ZBX_MAXEXECUTIONTIME: 500
      DB_SERVER_HOST: postgres-server
      ZBX_SERVER_HOST: zabbix-server  # Zabbix related and Php variables
    depends_on:
      - postgres-server
      - zabbix-server
    ports:    # Port where Zabbix UI is available
      - 8090:8080
    networks:
      zbx_net_backend:
       ipv4_address: 172.16.239.104
       aliases:
        - zabbix-web-pgsql
        - zabbix-web-ubuntu-pgsql
        - zabbix-web
      zbx_net_frontend:
       ipv4_address: 172.16.238.104

  adminer:  #Optional for accessing databases
     image: dockette/adminer
     restart: always
     ports:
       - 8084:80
     networks:
       zbx_net_backend:
         ipv4_address: 172.16.239.111
         aliases:
          - zabbix-adminer

networks:
  zbx_net_frontend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
  zbx_net_backend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    internal: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24
