# Loads default set of integrations. Do not remove.
default_config:

homeassistant:
  customize: !include customize.yaml

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

template: !include my-sensors/my-template-sensors.yaml